### PR TITLE
Rosace example

### PR DESCRIPTION
**Pull request by mkuo005**
Updated ROSACE Example

### CODE REVIEW

**Review by eyip002 — CHANGES_REQUESTED** [review]
Recheck the following event chains:
* ControlInput2
* Vzfilter2
* qfilter1

**Comment by mkuo005** [comment]
double checked and fix by adding new dependency

**Comment by eyip002** [comment]
> double checked and fix by adding new dependency

Is `Vz_control_Vzc: Vz_c → Vz_control.Vzc` a real dependency? I don't see it in the block diagram.
Same with the `ControlInput2: Vz_control_Vzc → delta_ec` event chain

**Comment by eyip002** [comment]
It’s from the simulink model, the external control has 3 inputs.
Vz_c is from the environment I.E. the control block in simulink

**Review by eyip002 — APPROVED** [review]

**Pull request merged**
